### ISSUE TITLE
部署Factory报错了

### ISSUE THREAD

**Issue by tianheng2017** [33357/uniswap-v2-contract#3]
PS C:\Users\tianh\Desktop\project\uniswap-v2-contract> yarn run env-cmd -f ./envs/env.bsctestnet yarn run hardhat UniswapV2:deploy --gas-price 5 --wait-num 1 --network 97
yarn run v1.22.22
$ C:\Users\tianh\Desktop\project\uniswap-v2-contract\node_modules\.bin\env-cmd -f ./envs/env.bsctestnet yarn run hardhat UniswapV2:deploy --gas-price 5 --wait-num 1 --network 97
$ C:\Users\tianh\Desktop\project\uniswap-v2-contract\node_modules\.bin\hardhat UniswapV2:deploy --gas-price 5 --wait-num 1 --network 97
{"level":30,"time":1726756412509,"pid":17972,"hostname":"12-29-2","msg":"deploy WETH9"}
{"level":30,"time":1726756412519,"pid":17972,"hostname":"12-29-2","msg":"skip transaction:0,deploy WETH9"}
{"level":30,"time":1726756412520,"pid":17972,"hostname":"12-29-2","msg":"WETH9 deployed proxy at 0x9e43D890091022F8d336dd556A1B7E4e670f8Ba9,impl at 0x9e43D890091022F8d336dd556A1B7E4e670f8Ba9,version 1.0.0,fromBlock 44011788"}
{"level":30,"time":1726756412520,"pid":17972,"hostname":"12-29-2","msg":"deploy UniswapV2Factory"}
{"level":30,"time":1726756412526,"pid":17972,"hostname":"12-29-2","msg":"execute operation transaction:1, deploy UniswapV2Factory, try 1"}
An unexpected error occurred:

ProviderError: max code size exceeded
    at HttpProvider.request (C:\Users\tianh\Desktop\project\uniswap-v2-contract\node_modules\.pnpm\hardhat@2.22.10_bufferutil@4.0.8_ts-node@10.9.2_@types+node@16.18.108_typescript@4.9.5__types_bcg7xnpe6opkidhlikokziquzi\node_modules\hardhat\src\internal\core\providers\http.ts:107:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async EthersProviderWrapper.send (C:\Users\tianh\Desktop\project\uniswap-v2-contract\node_modules\.pnpm\hardhat-deploy-ethers@0.3.0-beta.10_ethers@5.7.2_bufferutil@4.0.8_utf-8-validate@5.0.10__hard_u4gwodvwyxoqfgbpjgy45uirsq\node_modules\hardhat-deploy-ethers\src\internal\ethers-provider-wrapper.ts:13:20)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\tianh\Desktop\project\uniswap-v2-contract>

**Comment by tianheng2017** [comment]
修改参数后解决，哈哈哈，病急乱投医：
yarn run env-cmd -f ./envs/env.bsctestnet yarn run hardhat UniswapV2:deploy --gas-price 100 --wait-num 10 --network 97

**Comment by tianheng2017** [comment]
ε=(´ο｀*)))唉，合约验证又不行了，我太菜了。
PS C:\Users\tianh\Desktop\project\uniswap-v2-contract> yarn run env-cmd -f ./envs/env.bsctestnet yarn run hardhat UniswapV2:verify --network 97
yarn run v1.22.22
$ C:\Users\tianh\Desktop\project\uniswap-v2-contract\node_modules\.bin\env-cmd -f ./envs/env.bsctestnet yarn run hardhat UniswapV2:verify --network 97
$ C:\Users\tianh\Desktop\project\uniswap-v2-contract\node_modules\.bin\hardhat UniswapV2:verify --network 97
{"level":30,"time":1726757930788,"pid":15956,"hostname":"12-29-2","msg":"verify WETH9,implAddress: 0x9e43D890091022F8d336dd556A1B7E4e670f8Ba9"}
An unexpected error occurred:

Error: Cannot find module '@nomiclabs/hardhat-etherscan/dist/src/resolveEtherscanApiKey'
Require stack:
- C:\Users\tianh\Desktop\project\uniswap-v2-contract\node_modules\.pnpm\@openzeppelin+hardhat-upgrades@1.28.0_@nomiclabs+hardhat-etherscan@2.1.8_encoding@0.1.13_hard_kqk2du53fwklu4bmtqghbri4q4\node_modules\@openzeppelin\hardhat-upgrades\dist\utils\etherscan-api.js
- C:\Users\tianh\Desktop\project\uniswap-v2-contract\node_modules\.pnpm\@openzeppelin+hardhat-upgrades@1.28.0_@nomiclabs+hardhat-etherscan@2.1.8_encoding@0.1.13_hard_kqk2du53fwklu4bmtqghbri4q4\node_modules\@openzeppelin\hardhat-upgrades\dist\verify-proxy.js
- C:\Users\tianh\Desktop\project\uniswap-v2-contract\node_modules\.pnpm\@openzeppelin+hardhat-upgrades@1.28.0_@nomiclabs+hardhat-etherscan@2.1.8_encoding@0.1.13_hard_kqk2du53fwklu4bmtqghbri4q4\node_modules\@openzeppelin\hardhat-upgrades\dist\index.js
- C:\Users\tianh\Desktop\project\uniswap-v2-contract\hardhat.config.ts
- C:\Users\tianh\Desktop\project\uniswap-v2-contract\node_modules\.pnpm\hardhat@2.22.10_bufferutil@4.0.8_ts-node@10.9.2_@types+node@16.18.108_typescript@4.9.5__types_bcg7xnpe6opkidhlikokziquzi\node_modules\hardhat\internal\core\config\config-loading.js
- C:\Users\tianh\Desktop\project\uniswap-v2-contract\node_modules\.pnpm\hardhat@2.22.10_bufferutil@4.0.8_ts-node@10.9.2_@types+node@16.18.108_typescript@4.9.5__types_bcg7xnpe6opkidhlikokziquzi\node_modules\hardhat\internal\cli\cli.js
- C:\Users\tianh\Desktop\project\uniswap-v2-contract\node_modules\.pnpm\hardhat@2.22.10_bufferutil@4.0.8_ts-node@10.9.2_@types+node@16.18.108_typescript@4.9.5__types_bcg7xnpe6opkidhlikokziquzi\node_modules\hardhat\internal\cli\bootstrap.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1225:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (C:\Users\tianh\Desktop\project\uniswap-v2-contract\node_modules\.pnpm\@cspotcode+source-map-support@0.8.1\node_modules\@cspotcode\source-map-support\source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:1051:27)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\Users\tianh\Desktop\project\uniswap-v2-contract\node_modules\.pnpm\@openzeppelin+hardhat-upgrades@1.28.0_@nomiclabs+hardhat-etherscan@2.1.8_encoding@0.1.13_hard_kqk2du53fwklu4bmtqghbri4q4\node_modules\@openzeppelin\hardhat-upgrades\src\utils\etherscan-api.ts:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Object.require.extensions.<computed> [as .js] (C:\Users\tianh\Desktop\project\uniswap-v2-contract\node_modules\.pnpm\ts-node@10.9.2_@types+node@16.18.108_typescript@4.9.5\node_modules\ts-node\src\index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1288:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\tianh\\Desktop\\project\\uniswap-v2-contract\\node_modules\\.pnpm\\@openzeppelin+hardhat-upgrades@1.28.0_@nomiclabs+hardhat-etherscan@2.1.8_encoding@0.1.13_hard_kqk2du53fwklu4bmtqghbri4q4\\node_modules\\@openzeppelin\\hardhat-upgrades\\dist\\utils\\etherscan-api.js',
    'C:\\Users\\tianh\\Desktop\\project\\uniswap-v2-contract\\node_modules\\.pnpm\\@openzeppelin+hardhat-upgrades@1.28.0_@nomiclabs+hardhat-etherscan@2.1.8_encoding@0.1.13_hard_kqk2du53fwklu4bmtqghbri4q4\\node_modules\\@openzeppelin\\hardhat-upgrades\\dist\\verify-proxy.js',
    'C:\\Users\\tianh\\Desktop\\project\\uniswap-v2-contract\\node_modules\\.pnpm\\@openzeppelin+hardhat-upgrades@1.28.0_@nomiclabs+hardhat-etherscan@2.1.8_encoding@0.1.13_hard_kqk2du53fwklu4bmtqghbri4q4\\node_modules\\@openzeppelin\\hardhat-upgrades\\dist\\index.js',
    'C:\\Users\\tianh\\Desktop\\project\\uniswap-v2-contract\\hardhat.config.ts',
    'C:\\Users\\tianh\\Desktop\\project\\uniswap-v2-contract\\node_modules\\.pnpm\\hardhat@2.22.10_bufferutil@4.0.8_ts-node@10.9.2_@types+node@16.18.108_typescript@4.9.5__types_bcg7xnpe6opkidhlikokziquzi\\node_modules\\hardhat\\internal\\core\\config\\config-loading.js',
    'C:\\Users\\tianh\\Desktop\\project\\uniswap-v2-contract\\node_modules\\.pnpm\\hardhat@2.22.10_bufferutil@4.0.8_ts-node@10.9.2_@types+node@16.18.108_typescript@4.9.5__types_bcg7xnpe6opkidhlikokziquzi\\node_modules\\hardhat\\internal\\cli\\cli.js',
    'C:\\Users\\tianh\\Desktop\\project\\uniswap-v2-contract\\node_modules\\.pnpm\\hardhat@2.22.10_bufferutil@4.0.8_ts-node@10.9.2_@types+node@16.18.108_typescript@4.9.5__types_bcg7xnpe6opkidhlikokziquzi\\node_modules\\hardhat\\internal\\cli\\bootstrap.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by tianheng2017** [comment]
验证合约不行，我太菜了：


PS C:\Users\tianh\Desktop\project\uniswap-v2-contract> yarn run env-cmd -f ./envs/env.bsctestnet yarn run hardhat UniswapV2:verify --network 97
yarn run v1.22.22
$ C:\Users\tianh\Desktop\project\uniswap-v2-contract\node_modules\.bin\env-cmd -f ./envs/env.bsctestnet yarn run hardhat UniswapV2:verify --network 97
$ C:\Users\tianh\Desktop\project\uniswap-v2-contract\node_modules\.bin\hardhat UniswapV2:verify --network 97
failed to get chainId, falling back on net_version...
An unexpected error occurred:

ConnectTimeoutError: Connect Timeout Error
    at onConnectTimeout (C:\Users\tianh\Desktop\project\uniswap-v2-contract\node_modules\.pnpm\undici@5.28.4\node_modules\undici\lib\core\connect.js:186:24)
    at C:\Users\tianh\Desktop\project\uniswap-v2-contract\node_modules\.pnpm\undici@5.28.4\node_modules\undici\lib\core\connect.js:133:46
    at Immediate._onImmediate (C:\Users\tianh\Desktop\project\uniswap-v2-contract\node_modules\.pnpm\undici@5.28.4\node_modules\undici\lib\core\connect.js:172:33)
    at processImmediate (node:internal/timers:483:21) {
  code: 'UND_ERR_CONNECT_TIMEOUT'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
